[theme]
primaryColor="green" # cor de destaque (bordas, slider) do app
backgroundColor="#55DDBB" # cor de fundo das páginas
secondaryBackgroundColor="rebeccapurple" # cor secundária dos fundos das páginas (menu, tabelas, etc.)
textColor="#FFFFFF" # cor do texto do app
font="monospace" # fonte do app